#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32

def subscriber():
	sub=rospy.Subscriber('/sonar_dist',Float32,callback_function)

	rospy.spin()

def callback_function(message):
	rospy.loginfo("Distance : %f"%message.data)

if __name__ == "__main__":
	rospy.init_node("subs")
	subscriber()
	
