#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
import rospy
from std_msgs.msg import Float32
GPIO.setmode(GPIO.BCM)
GPIO.setup(18, GPIO.OUT)
pwm = GPIO.PWM(18, 100)
pwm.start(2.5)
GPIO.setwarnings(False)


def subscriber():
	sub=rospy.Subscriber('/sonar_dist',Float32,callback_function)

	rospy.spin()

def callback_function(message):
	rospy.loginfo("Distance : %f"%message.data)
	if message.data < 20 :
		pwm.ChangeDutyCycle(15)
	elif message.data > 20 :
		pwm.ChangeDutyCycle(5)
		
if __name__ == "__main__":
	rospy.init_node("subs")
	subscriber()

while not rospy.is_shutdown():
    continue

GPIO.output(18,False)
